Bug/in game qam alignment
EMERALD0874/Steam-Deck-Themes pull request #76
Opened 2024-01-17 23:36 UTC by rnikoopour

Fixes visual issue described in #75

2024-01-18 04:25 UTC, EMERALD0874 requested changes
Obsidian should recolor, not remove, elements in the UI. Are you able to change this so it only modifies the color?

2024-01-18 15:46 UTC, rnikoopour commented
Thank you for the feedback.  I adjusted the PR as requested.

2024-01-18 15:47 UTC, rnikoopour commented
I'm going to squash my commits and force push my branch.  My commit history got weird on this one due to some work I was doing on my side.

2024-02-19 15:27 UTC, EMERALD0874 approved these changes

2024-02-19 15:27 UTC, merged