OBSIDIAN - Lockscreen Background
EMERALD0874/Steam-Deck-Themes pull request #8
Opened 2022-07-28 12:23 UTC by Ian-Boraks

Made the lockscreen background adhere to the obsidian theme.

```css
.lockscreen_Container_3rFFU {
  background: var(--obsidian-main-color) !important;
}
```

2022-07-28 13:11 UTC, Ian-Boraks commented
Filter Rounding:
![Normal View](https://user-images.githubusercontent.com/31255827/181512927-e79210b8-1c91-405a-b2ac-3e4e3bdbbc3a.png)
![Advanced View](https://user-images.githubusercontent.com/31255827/181513001-7814b62b-b25d-4ed0-b8e7-ab6d858bec43.png)

---

Controller Setting Rounding
![Browse Community](https://user-images.githubusercontent.com/31255827/181513250-5bb43a12-ecd3-4a0e-8a62-d22fac6c286d.png)
![Layouts](https://user-images.githubusercontent.com/31255827/181513327-1e7a1430-5bec-45bb-b46c-a5cef77e006a.png)

2022-07-28 13:11 UTC, Ian-Boraks commented on Round/shared.css
> +}
These are for the filter changes

2022-07-28 13:12 UTC, Ian-Boraks commented on Round/shared.css
>  }
Controller Layouts

2022-07-28 15:10 UTC, Ian-Boraks commented
Rounded Friends in Search
![Rounded Friends in Search](https://user-images.githubusercontent.com/31255827/181573148-5b076edd-28f7-4f42-912c-913925a99fc3.png)

2022-07-28 15:12 UTC, Ian-Boraks commented on Round/shared.css
> +}
Rounded friends in search

2022-07-28 15:27 UTC, EMERALD0874 requested changes
Lock screen fix for Obsidian has already been made. Please remove this from your PR as it would create redundant styling.

2022-07-28 16:03 UTC, Ian-Boraks commented
Reverted Commit for Lock-screen in Obsidian

2022-07-28 17:02 UTC, EMERALD0874 requested changes
For consistency with the library filters, could you make each individual section of the game options (play through developer, properties, cancel) rounded? I know I said I wasn't a huge fan when I tested it before but I think I've been swayed into liking it.

Also, do you mind increasing the theme.json one minor version to 1.3?

2022-07-29 03:40 UTC, EMERALD0874 approved these changes
LGTM

2022-07-29 03:40 UTC, merged